language: node_js
sudo: false
node_js:
  - "6"
  - "7"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - ./scripts/webdriver.sh
  - ./scripts/testserver.sh

script:
  - TEST_BROWSER_NAME=firefox npm test
